### ISSUE TITLE
Build(s) broken

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#494]
See https://dashboard.heroku.com/apps/ably-docs/activity/builds/979fe947-69c1-49c6-b14f-733586f88d5d

```
-----> Compiling nanoc site
Captain! We’ve been hit!
Message:
TypeError: no implicit conversion of nil into String
Compilation stack:
  (empty)
Stack trace:
  0. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/Rules:87:in `+'
  1. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/Rules:87:in `block in parse'
  2. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/rule.rb:68:in `instance_eval'
  3. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/rule.rb:68:in `apply_to'
  4. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/compiler.rb:239:in `block (2 levels) in route_reps'
  5. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/compiler.rb:237:in `each_pair'
  6. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/compiler.rb:237:in `block in route_reps'
  7. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/compiler.rb:232:in `each'
  8. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/compiler.rb:232:in `route_reps'
  9. /tmp/build_19b70bdb78ab0f0eaac9cc4253cc0b26/vendor/bundle/ruby/2.4.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/compiler.rb:123:in `load'
  ... 33 more lines omitted. See full crash log for details.
If you believe this is a bug in nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-
A detailed crash log has been written to ./crash.log.
       Loading site data…  !     Push rejected, failed to compile nanoc app.
```

**Comment by Srushtika** [comment]
@mattheworiordan @tomczoink This was my mistake. 

I did a merge of the WebRTC tutorial with an issue in file name which broke the build. I had tested it locally before but missed re-checking after updating a few file names.

I found out yesterday and this was successfully fixed before the WebRTC tutorial was deployed on the website. Apologies, I'll be extra careful henceforth.

@tomczoink can you please confirm if everything looks good on your end too, so we can close this issue?

**Comment by tomczoink** [comment]
@Srushtika @mattheworiordan not seeing anything wrong since then.
