### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#776]
```
#<Thread:0x000055fc0bd10418@/tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-core-4.11.2/lib/nanoc/core/notification_center.rb:29 run> terminated with exception (report_on_exception is true):
/tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/ddmetrics-1.0.1/lib/ddmetrics/stopwatch.rb:29:in `start': Cannot start, because stopwatch is already running (DDMetrics::Stopwatch::AlreadyRunningError)
	from /tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-4.11.2/lib/nanoc/cli/commands/compile_listeners/file_action_printer.rb:32:in `block in start'
	from /tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-4.11.2/lib/nanoc/cli/commands/compile_listeners/abstract.rb:55:in `block in on'
	from /tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-core-4.11.2/lib/nanoc/core/notification_center.rb:40:in `block (3 levels) in start'
	from /tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-core-4.11.2/lib/nanoc/core/notification_center.rb:39:in `each'
	from /tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-core-4.11.2/lib/nanoc/core/notification_center.rb:39:in `block (2 levels) in start'
	from /tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-core-4.11.2/lib/nanoc/core/notification_center.rb:32:in `loop'
	from /tmp/build_f3dcab8ef27e967f94dbcb870d43eb24/vendor/bundle/ruby/2.6.0/gems/nanoc-core-4.11.2/lib/nanoc/core/notification_center.rb:32:in `block in start'
-----> Timed out running buildpack nanoc
 !     Push failed
```

**Comment by tomczoink** [comment]
I've not seen this reproduced since this one time, so doesn't appear to be a reoccuring issue thankfully.
